### ISSUE TITLE
Player One no forward movement

### ISSUE THREAD

**Issue by NML32** [MiSTer-devel/Arcade-Ultratank_MiSTer#1]
Player one forward movement doesn't work. Pressing up on the joystick for player one doesn't move the tank. Arcade-Ultratank_20200120.rbf

Thank you for porting Ultratank to the MiSTer.

**Comment by NML32** [comment]
I see you fixed player one forward movement with build Arcade-Ultratank_20200128.rbf. 
Now there seems to be a problem with the two-player game. 
After inserting two credits and selecting two players the upper left still says Robot and it's moving forward and crashing into a wall.

**Comment by neurorulez** [comment]
I think is fixed now. Test it and say if work for you.
To start a 2 player game you must press 1 and 2 larer. Having 2 on more coins inserted. I play with both players and work to me.

**Comment by NML32** [comment]
Thank you, everything seems to be working correctly. 
I was pressing 2 for two players (my mistake). 
Taking your advice pressing 1 and 2 for a two-player game works. :)
